jhipster-dev-mysql:
  container_name: license-dev-mysql
  image: mysql
  # volumes:
  # - ~/volumes/jhipster/license/dev-mysql/:/var/lib/mysql/
  environment:
  - MYSQL_USER=root
  - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  - MYSQL_DATABASE=license
  ports:
  - "3306:3306"
  command: mysqld --lower_case_table_name=1

